/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 1280
      height: 720
      scale: 0.5
      fx: 1108.5125
      fy: 854.51674
      cx: 640.0
      cy: 360.0
      d0: 0.0
      d1: 0.0
      d2: 0.0
      d3: 0.0
