/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 1280
      height: 1024
      scale: 1.0
      fx: 1299.7654648406829
      fy: 1299.0356448877542
      cx: 622.0895165429051
      cy: 497.5915259505117
      d0: -0.0822706582390632
      d1: 0.11989667288080653
      d2: 0.0009870994051046369
      d3: -0.004930977358867424
